fail_fast: true
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer

  - repo: local
    hooks:
      - id: check-file-pair
        name: check-file-pair
        language: system
        entry: uv tool run devobs check-file-pair
        pass_filenames: false
        args:
          - --from=pydantic_fixedwidth
          - --to=tests
          - --include=*.py
          - --exclude=errors.py,_*.py
          - --expect={to}/{relative_from}/test_{filename}
          - --create-if-not-exists

      - id: ruff-check
        name: ruff check
        language: system
        types: [python]
        entry: uv run ruff check
        args: [--fix]

      - id: ruff-format
        name: ruff format
        language: system
        types: [python]
        entry: uv run ruff format

      - id: mypy
        name: mypy
        language: system
        types: [python]
        pass_filenames: false
        entry: uv run mypy
        args: [--show-error-codes, --pretty, .]

      - id: pytest
        name: pytest
        language: system
        types: [python]
        pass_filenames: false
        entry: uv run pytest
